---
sudo: required
dist: bionic

language: python
python:
  - 3.8

services:
  - docker

cache:
  directories:
    - vendor/bundle
    - $HOME/.cache/pip
    - $HOME/.local
    - roles

jobs:
  include:
    - stage: Spec
      name: Bionic
      env: ANSIBLE_VERSION="2.9" ENVIRONMENT_NAME=bionic
      script: bundle exec rake spec:$ENVIRONMENT_NAME

    - name: Legacy Parameters
      env: ANSIBLE_VERSION="2.5" ENVIRONMENT_NAME=xenial ANSIBLE_PYTHON_VERSION=2
      python: 2.7
      script: bundle exec rake spec:$ENVIRONMENT_NAME

    - stage: Idempotence
      name: MySQL
      env: ANSIBLE_VERSION="2.9" ENVIRONMENT_NAME=bionic INSTALL=mysql
      script: ./idempotence.sh
    - name: MariaDB
      env: ANSIBLE_VERSION="2.9" ENVIRONMENT_NAME=bionic INSTALL=mariadb
      script: ./idempotence.sh
    - name: Percona
      env: ANSIBLE_VERSION="2.9" ENVIRONMENT_NAME=bionic INSTALL=percona
      script: ./idempotence.sh

    - name: Legacy Parameters
      env: ANSIBLE_VERSION="2.5" ENVIRONMENT_NAME=xenial ANSIBLE_PYTHON_VERSION=2 INSTALL=mysql
      python: 2.7
      script: ./idempotence.sh

before_install:
  - docker pull ubuntu:${ENVIRONMENT_NAME}

  - travis_retry bundle install --deployment

install:
  - travis_retry pip install -U ansible==${ANSIBLE_VERSION}.*

  - travis_retry ansible-galaxy install -r roles.yml

  - travis_wait bundle exec rake environment:${ENVIRONMENT_NAME}:provision

after_script:
  - bundle exec rake environment:destroy

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
